hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [main]

    # https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/2-configuring_resource_owners.md
    resource_owners:
        azure:
            type:                azure
            client_id:           '%env(AD_ID)%'
            client_secret:       '%env(AD_SECRET)%'
            scope:               User.Read offline_access
            options:
                # display: popup
                csrf: true
                refresh_on_expire: true
                application: common
                infos_url: https://graph.microsoft.com/v1.0/me
