vich_uploader:
    db_driver: orm


    mappings:
        workshop_image:
            uri_prefix: /images/workshops
            upload_destination: '%kernel.project_dir%/public/images/workshops'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true

        payment_file:
            uri_prefix: /images/paymentFile
            upload_destination: '%kernel.project_dir%/public/images/paymentFile'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
#            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
