controllers:
    resource: ../src/Controller/
#        path: resource:
#        namespace: App\Controller
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: en|fr
    defaults:
        _locale: en

#controllers:
#    resource: ../src/Controller/
#    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation



nbgrp_saml:
    resource: "@NbgrpOneloginSamlBundle/Resources/config/routes.php"



theme_show_all:
    path: /{_locale}
    requirements:
        _locale: en|fr
    defaults:
        _locale: fr
    controller: App\Controller\SelfcareController::show