# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.clicktopay_reg: '%env(CLICKTOPAY_REG)%'
    app.clicktopay_os: '%env(CLICKTOPAY_OS)%'
    app.msc_dns: '%env(MSC_DNS)%'
    maintenance_file: '%kernel.project_dir%/public/.maintenance'
    payment_file: '%kernel.project_dir%/public/images/paymentFile'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        # Créer un alias direct pour la classe Gedmo
    Gedmo\Translatable\TranslatableListener: '@stof_doctrine_extensions.listener.translatable'

        # Votre LocaleListener sera automatiquement configuré grâce à l'alias ci-dessus
    App\EventListener\LocaleListener:
        arguments:
            $translatableListener: '@stof_doctrine_extensions.listener.translatable'
            tags:
                - { name: kernel.event_listener, event: kernel.request, priority: 15 }


    my.oauth_aware.user_provider.service:
        class: App\Security\UserProviderAzure
    saml_user_factory:
        class: App\Security\UserFactory




    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
#    App\EventListener\MaintenanceListener:
#        arguments:
#            - '%maintenance_file%'
#            - '@twig'
#        tags:
#            - { name: kernel.event_listener, event: kernel.request }
